### PR TITLE
Add ActiveSupport Numeric time extensions.

### PR DESCRIPTION
**Pull request by frewsxcv**
Everything in this file:

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/numeric/time.rb

### CODE REVIEW

**Comment by ghiculescu** [comment]
This doesn't play nicely with `sorbet-rails` for me. For example, if you have an integer column, `sorbet-rails` generates this:

```ruby
  sig { params(value: T.nilable(Integer)).void }
  def update_interval=(value); end
```

With this update, this code no longer works:

```ruby
  foo.update_interval = 1.day
```

Instead it gets `Assigning a value to value that does not match expected type T.nilable(Integer)`.

Assuming you use Rails, how are you handling this @frewsxcv ?

**Comment by ghiculescu** [comment]
My best idea so far is to change https://github.com/chanzuckerberg/sorbet-rails/blob/master/lib/sorbet-rails/model_plugins/active_record_attribute.rb#L95 to return multiple types, so it would return `T.any(Integer, ActiveSupport::Duration)`.

Or to add a `.to_i` in the code that's erroring.

**Comment by elliottt** [comment]
Should we revert this?

**Comment by frewsxcv** [comment]
> My best idea so far is to change https://github.com/chanzuckerberg/sorbet-rails/blob/master/lib/sorbet-rails/model_plugins/active_record_attribute.rb#L95 to return multiple types, so it would return `T.any(Integer, ActiveSupport::Duration)`.

Agreed. This should be fixed in sorbet-rails 👍

**Comment by ghiculescu** [comment]
Cool, working on an improvement here: https://github.com/chanzuckerberg/sorbet-rails/pull/223

**Pull request merged**
