### PR TITLE
Add some methods to activerecord.rbi that are used in migrations.

### PR DESCRIPTION
**Pull request by connorshea**
I noticed a lot of my migration files weren't typed simply because Sorbet didn't know about a lot of these methods, so I've fixed that.

https://edgeguides.rubyonrails.org/active_record_migrations.html

### CODE REVIEW

**Comment by connorshea** [comment]
This is still missing a few methods, e.g. extensions, reversible, execute, and timestamps. I’ll add those when I get a chance tonight.

**Comment by connorshea** [comment]
This should be good to go now 👍

**Comment by connorshea** [comment]
Correction: I need to do a bit more work on this to make sure everything works. I'm missing a lot of options from the `*options` parameters in these.

**Comment by connorshea** [comment]
On my Rails app, this change causes `bundle exec srb tc --typed=true --ignore spec/` to go from 240 errors to 109 🎉

**Comment by DarkDimius** [comment]
> On my Rails app, this change causes bundle exec srb tc --typed=true --ignore spec/ to go from 240 errors to 109 🎉


wow, this is awesome! Thank you!

**Pull request merged**
