### PR TITLE
Add test files for actionpack, activemodel, activerecord, and activesupport

### PR DESCRIPTION
**Pull request by connorshea**
I have no idea what this does to sorbet if this is merged and you try to update sorbet-typed.

I've included an intentionally failing method to show that this is working. However, it only allows files that have no type errors, there's no way to test that sorbet catches incorrect code.

This is a simplified version of my `routes.rb` file that I showed in #95.

The idea to do this was started by #42 and re-upped in #102 by @panthomakos.

cc: @DarkDimius @jez I know this isn't the test harness you wanted, and I'd still like to get that eventually, but I'm curious if you think this solution would be workable? Do you see any significant flaws with this approach?

### CODE REVIEW

**Comment by connorshea** [comment]
I changed the git remote of sorbet-typed in my `/.cache/sorbet/sorbet-typed` directory, and it does not pull in anything from `test/` as far as I can tell

**Comment by connorshea** [comment]
Alright, I've added more tests and explained how the tests work in the README. Plus I've fixed a few bugs I found with the existing signatures :) This should be good to review now.

**Comment by connorshea** [comment]
@panthomakos 👍 you should open a PR to change that, it looks like a good idea (though I'd prefer if the files were named `gem_name_test.rb` still, and you'll have to check whether Sorbet pulls down the files properly when you organize the project like that.

You can go into `.cache/sorbet/sorbet-typed/` and use `git remote set-url origin URL_GOES_HERE` to change the git remote that Sorbet uses to get sorbet-typed stuff, and you'll also need to merge the change into the master branch on your fork since sorbet-typed can't be configured to use a different branch. Then update the sorbet-typed files in a project and you'll get whatever is in your fork of the project.

I really should open an issue to make this easier...

**Comment by panthomakos** [comment]
Thank you for the write-up. I'll put a PR together!

**Pull request merged**
