### PR TITLE
Add rspec-core

### PR DESCRIPTION
**Pull request by dduugg**
Adds `rspec-core`, in order to pick up `RSpec::Core::RakeTask`, which isn't inferred by `srb`, but is a [common](https://github.com/search?q=RSpec%3A%3ACore%3A%3ARakeTask&type=code) incantation.

1st commit: adds a test
2nd commit: adds the autogenerated `rspec-core`
3rd commit: adds `RSpec::Core::RakeTask`

One potential hiccup is that the class inherits `::Rake::TaskLib`, which isn't found in this repo, or in the autogenerated `Rake` code, but doesn't seem to present issues (tests pass locally as well as in a project that uses `RSpec::Core::RakeTask`).

### CODE REVIEW

**Comment by jez** [comment]
> One potential hiccup is that the class inherits `::Rake::TaskLib`, which isn't found in this repo, or in the autogenerated `Rake` code, but doesn't seem to present issues (tests pass locally as well as in a project that uses `RSpec::Core::RakeTask`).

I believe that CI is failing for precisely this reason?

There's a way in the test runner for sorbet-typed to say that one file depends on another file when testing.

You might want to autogenerate the rake RBI and include that in this PR or another PR.

**Comment by dduugg** [comment]
I've opened up a separate PR to add `rake`: https://github.com/sorbet/sorbet-typed/pull/333

**Review by jez — APPROVED** [review]
ty

**Comment by connorshea** [comment]
Out of curiosity, why add everything here rather than just what's specifically necessary to get this working? This makes it more likely that this will break in the future or will cause conflicts with other generated types.

**Comment by dduugg** [comment]
@connorshea Great question! This seemed consistent with the instructions at the top of autogenerated sorbet rbi files:

```
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/$REST_OF_PATH
```

However, I'm seeing that `bundle exec srb rbi gems` still creates the autogenerated file even if the corresponding `sorbet-typed` file exists. Confusingly, the `sorbet-typed` file is then marked `# typed: ignore`, but the project still typechecks, despite necessary constants being defined in the now-ignored file (tested on https://github.com/dduugg/yard-sorbet).

Please feel free to open a ticket/PR to fix/clarify the intended use of the library. I'm going to reach out to the project maintainers to better understand things.

**Pull request merged**
